//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemKadr.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KadryDBEntities : DbContext
    {
        public KadryDBEntities()
            : base("name=KadryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Godziny_przepracowane> Godziny_przepracowane { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Wydzialy> Wydzialy { get; set; }
        public virtual DbSet<Wyplaty> Wyplaty { get; set; }
    }
}
